version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: geolocation_api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      GATEWAY_PORT: 8888
    ports:
      - "8888:8888"
    depends_on:
      - db
    networks:
      - geolocation
  importer:
    build:
      context: .
      dockerfile: cmd/importer/Dockerfile
    container_name: importer
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      IMPORT_FROM: cmd/importer/data_dump.csv
    networks:
      - geolocation
  db:
    image: postgres:latest
    container_name: geolocation_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - geolocation
networks:
  geolocation: